### ISSUE TITLE
Is a concurrent sorted set planned ?

### ISSUE THREAD

**Issue by nhaberl** [stewienj/SwordfishCollections#12]
I would need a thread safe sorted set as a cache inside my asp.net app.

Want to get a set of objects based on an enumerable in a specific sort order.

**Comment by stewienj** [comment]
Hi @nhaberl 
This library already has ConcurrentObservableSortedCollection, I normally think of a set as an unordered collection, but there are other features. Are you looking for these:
- all items in a set are unique
- you can do set operations like union, intersect, except, and exclusive (opposite of union)

I'm thinking a solution would be do something like a sorted version of ConcurrentObservableHashSet

**Comment by nhaberl** [comment]
Yes exactly, similar to Redis sorted sets.
My use case is the following

Get n items from a bitmap index and based on them I would like to retrieve objects from the set (or sets) in a predefined order.

Concretely I wanna cache a list of words based on frequency in my domain.
It would be even greater if the API supports top k elements. 

All in all its for a lookup engine.

**Comment by stewienj** [comment]
@nhaberl every collection in this library is backed by an immutable collection. The GUI needs to do multiple passes sometimes of the collection, and if you modify the collection during those passes then you break the GUI, however I don't want to block updates to the collections while the GUI is updating, so I hand the GUI an immutable collection, which is also the backing of the concurrent collection. Works quite well and seems very performant.

**Comment by nhaberl** [comment]
Ok, have you ever tested with millions ob objects ?
In a high concurrent environment ?

**Comment by stewienj** [comment]
Yes I have one of those environments, and it broke the original implementation, which is also contained in this repo. It also broke version 2, so I didn't bother publishing that version. Version 3, labeled as V3, seems to handle the load.

**Comment by nhaberl** [comment]
Sorry for asking ... are you planning to add a sorted set also ?
Would be an awesome addition.

**Comment by stewienj** [comment]
Yes I'm planning to add a sorted set, I'm going to base it on System.Collections.Immutable.ImmutableSortedSet<T> from the following nuget package that this project already has a dependency on:
https://www.nuget.org/packages/System.Collections.Immutable/1.7.1
Might take me a couple of days before I can fit it in.

**Comment by nhaberl** [comment]
Sounds fantastic!!

**Comment by stewienj** [comment]
I'm in the process of testing the implementation. The inputs are 10 collections, each holding 1 million items each. Here's the timings:

Generating Test Input Collections
Duration 00:00:00.1504973

The above creates 10 List<T> collections, each holding 1,000,000 items

Generating Expected Output
Duration 00:00:00.5899992

The above aggregates the lists, extracts the unique items, and sorts them.

Timing adding everything to normal sorted set
Duration 00:00:03.4828527

The above tests adding the 10 million items to a normal sorted set.

Timing adding everything to an immutable sorted set
Duration 00:00:04.1894225

The above tests adding the 10 million items to an immutable sorted set, as you can see the immutability adds very little overhead.

Adding items to test subject
Duration 00:00:13.3132126

The above is adding the 10 million items to my ConcurrentObservableSortedSet<T> implementation, done from 10 threads, 1 million items per thread. Seems the overhead of synchronizing access to the underlying immutable sorted set triples the time required. A reasonable trade-off for the convenience I think.

**Comment by stewienj** [comment]
I still need to write some more unit tests, but I figured I'd publish it anyway as the changes won't break anything else.

Nuget package has been published, version 3.2.0.

**Comment by nhaberl** [comment]
Looks really good. Did you also check garbage collection?

**Comment by stewienj** [comment]
> Did you also check garbage collection?
No I've never considered that a risk, but I can put something into a unit test.

**Comment by stewienj** [comment]
Forgot to close this issue 17 months ago
