### ISSUE TITLE
ConcurrentObservableSortedCollection Mathod "Reset" Without Sort

### ISSUE THREAD

**Issue by Kannagi0303** [stewienj/SwordfishCollections#17]
use Reset() result is not sorted.
AddRange is no problem.

**Comment by stewienj** [comment]
Good catch! Yes I've overridden AddRange(), but I didn't override Reset(). I'll fix this in the morning (12 hours time) when my head is clearer.

**Comment by stewienj** [comment]
New nuget version is here https://www.nuget.org/packages/Swordfish.NET.CollectionsV3/3.3.6
