### ISSUE TITLE
IEqualityComparer<T> HashSet & SortedSet

### ISSUE THREAD

**Issue by GammaSoul** [stewienj/SwordfishCollections#22]
Hi Awsome Library!
Is it possible to implement IEqualityComparer<T> on both your HashSet and SortedSet Collections?
Thanks

**Comment by stewienj** [comment]
That should be doable. The ConcurrentObservableHashSet has ImmutableHashSet underneath, which has SetEquals() for comparing collections, so I can wrap that with some type checking around it. Same with ConcurrentObservableSortedSet. I'll try to find some time over the next couple of days to do it, write some unit tests, and then publish a new nuget package.

**Comment by GammaSoul** [comment]
Wow! Awesome! thank you. i did not expect a reply so fast to this! Please dont put your self out on my account. But it will be great for this to be added to this already awesome library! Thanks again!

**Comment by stewienj** [comment]
It just occurred to me I might be going down the wrong track here. I started implementing these two classes:
```
public class ConcurrentObservableHashSetComparer<T> : IEqualityComparer<ConcurrentObservableHashSet<T>>

public class ConcurrentObservableSortedSetComparer<T> : IEqualityComparer<ConcurrentObservableSortedSet<T>>
```
But I was wondering what the use case would be, then it dawned on me what you probably wanted is the ability to pass in the comparer in the constructor right?
```
public ConcurrentObservableHashSet(IEqualityComparer<T> comparer)

public ConcurrentObservableSortedSet(IEqualityComparer<T> comparer)
```

**Comment by stewienj** [comment]
Implemented the constructors, wrote and ran some unit tests which all passed. Published a nuget package, so it's al done!
Here's the updated nuget package https://www.nuget.org/packages/Swordfish.NET.CollectionsV3/3.3.9
