### ISSUE TITLE
Wrong event fired on `ConcurrentObservableSortedSet.Remove`

### ISSUE THREAD

**Issue by longnguyen2004** [stewienj/SwordfishCollections#23]
https://github.com/stewienj/SwordfishCollections/blob/ec3a8abca26742231dad6f66e8fc18513584b6d5/Swordfish.NET.CollectionsV3/ConcurrentObservableSortedSet.cs#L75-L88

This should be `NotifyCollectionChangedAction.Remove`, not `NotifyCollectionChangedAction.Add`

**Comment by stewienj** [comment]
Good catch. Thanks for your pull request https://github.com/stewienj/SwordfishCollections/pull/24 which I have merged in. A new nuget package containing your fix has been published here https://www.nuget.org/packages/Swordfish.NET.CollectionsV3/3.3.10
