### ISSUE TITLE
[New Feature Request] Add new constructors that take IEnumerable<T> or List<T>

### ISSUE THREAD

**Issue by Setsu-BHMT** [stewienj/SwordfishCollections#27]
Basically I'm using ConcurrentObservableCollection as a drop-in replacement for ObservableCollection, and was surprised that it doesn't provide constructors that take some kind of IEnumerable. This is mostly a nice to have that allows initializing code to be moved out of the constructor, like this:

`public ConcurrentObservableCollection<int> MyCollection { get; init; } = new(new int[4]);`

**Comment by stewienj** [comment]
I guess you must be using version 3, as in version 2 I had a constructor that took an enumerable, and now version 3 has a constructor that takes an enumerable. New version is 3.3.12 and you can pull it from the master branch, or grab the new nuget package which I just confirm is published here https://www.nuget.org/packages/Swordfish.NET.CollectionsV3/3.3.12

**Comment by Setsu-BHMT** [comment]
Wow you work fast! Much appreciated thanks (Yes I'm using v3)
