### ISSUE TITLE
Things that could be done

### ISSUE THREAD

**Issue by fjch1997** [stewienj/SwordfishCollections#3]
This is an awesome library. Been using it for a year now so it feels right to contribute

1. Make everything serializable
2. ~~Write a nuspec file and push it to NuGet. Replace the old unofficial one.~~
3. Make it portable
4. All the collection under Swordfish.NET.Collections does not implement `INotifyPropertyChanged` to signal `Count` change
5. ~~Remove log4net it just doesn't make sense~~
6. Properly implement ICollection.SyncRoot so we can use something like the following
```
ConcurrentObservableCollection<MyObject> collection = GetSomeCollection();
Predicate<MyObject> predicate = GetSomePredicate();
lock (((System.Collections.ICollection)collection).SyncRoot)
{
    if (collection.Any(i => predicate(i)))
        collection.Add(GetMyObject());
}
```
This is something similar to ConcurrentDictionary.TryAdd()

I already did 2, 5 and part of 1 in my forked repo. Will put more work on it if people agree and consider them to be useful

**Comment by stewienj** [comment]
I only just noticed your fork. I've reviewed the changes you've done and merged them into my repo.

Thank you for your efforts. It motivates me to pay more attention to this code.

I've done some refactoring, as things stand there are 3 libraries and a test project:

- Swordfish.NET.Collections.csproj - this is a standalone project holding the old concurrent collection classes, that I'm calling version 2, and that I wrote a code project article for.
- CollectionsV3\Swordfish.NET.CollectionsV3.csproj - this is a new take on the old goal, but is potentially a Portable Class Library, and is also a better approach in my opinion.
- Swordfish.NET.csproj - this is some other code that the new V3 collection classes depend on that isn't specifically aimed at collections. It's a subset of another project I've been working on.
- Test\Swordfish.NET.Test.csproj - A WPF project that allows some rudimentary testing of the collection classes.

I've gone through the new code and removed any dependencies on log4net, and I've removed some references with an aim towards making the code more portable. 

Number 4 - raising a property changed event when count changes, has been implemented in the new V3 collections. This gets raised anytime the collection is changed, however the rate that it is fired is throttled to once every 20 milliseconds.

I don't have any experience with producing nuget packages. Currently the nuspec file is included in Swordfish.NET.csproj. I take it we'll need to produce nuspec files for each DLL?

**Comment by fjch1997** [comment]
Do you think now is a good time to pack the v1 v2 collections under SwordfishCollections/Collections into a package and push it up to nuget.org?

**Comment by stewienj** [comment]
Yes, I’m not doing anymore work on that version myself, so it can be published as is.

**Comment by stewienj** [comment]
Oops, replied to that from my phone by email and included everything.

**Comment by stewienj** [comment]
Yes, I’m not doing anymore work on that version myself, so it can be published as is.
