### ISSUE TITLE
Fails to bind ConcurrentObservableDictionary to Maui CollectionView on Windows

### ISSUE THREAD

**Issue by WisJamison** [stewienj/SwordfishCollections#33]
Hi @stewienj 

Originally i bind a ConcurrentObservableDictionary to StackLayout and everything works good in a maui project. When I wanna to  replace StackLayout with CollectionView. The binding fails with below error. 

<img width="957" alt="image" src="https://github.com/stewienj/SwordfishCollections/assets/100921425/77e1d0f6-d1dd-4804-af0e-397c8189c204">

Can you guys take a look at and to see if anything i have missed. Thank you in advance.

Please refer to this repo for more details: https://github.com/WisJamison/Maui-CollectionView-Sample

**Comment by stewienj** [comment]
Hi @WisJamison the image you posted seems very blurry, so I can't see your exact error. I'm not aware of anyone else using this collection library with Maui, this library is pretty old and was designed for use with WPF, that said I can't see any reason why it wouldn't work with Maui. There is a bit of a trick to binding to any of the collections, where you need to bind to ConcurrentObservableDictionary as the source, and then you need to specify a path to CollectionView. Here's the example from the readme.md showing the Xaml as it would appear in a WPF project where TestCollection would be your ConcurrentObservableDictionary in your view model:
```xml
<!-- ListView binds to TestCollection.CollectionView -->
<ListView ItemsSource="{Binding TestCollection.CollectionView}" Grid.Row="1" Grid.Column="0" />
```

**Comment by stewienj** [comment]
I had a look at your source code, the problem could be here:
https://github.com/WisJamison/Maui-CollectionView-Sample/blob/457d93af132284a16c8a0333492cc5b7b0a1ecb5/CollectionViewChildEvents/MainPage.xaml#L14
Try changing that line to:
```xml
ItemsSource="{Binding ImageList.CollectionView}"
```

**Comment by WisJamison** [comment]
> I had a look at your source code, the problem could be here: https://github.com/WisJamison/Maui-CollectionView-Sample/blob/457d93af132284a16c8a0333492cc5b7b0a1ecb5/CollectionViewChildEvents/MainPage.xaml#L14 Try changing that line to:
> 
> ```
> ItemsSource="{Binding ImageList.CollectionView}"
> ```

Hi @stewienj Thanks for your update. Are you sure it works good by this change on your end? I continue to face the same issue on my side. 
`Error: Cannot get 'Item' value (type 'Object') from type 'Microsoft.Maui.Controls.Platform.ItemTemplateContext'. BindingExpression: Path='Item' DataItem='Microsoft.Maui.Controls.Platform.ItemTemplateContext'; target element is 'Microsoft.Maui.Controls.Platform.ItemContentControl' (Name='ItemContentControl'); target property is 'FormsDataContext' (type 'Object').`

**Comment by WisJamison** [comment]
Hi @stewienj  Nvm, Maui team has confirm that's a bug on maui-CollectionView. We can't not even bind a primary Dictionary with objects. 

Anyway, thanks for your help.

**Comment by stewienj** [comment]
Thanks for the update, I have been looking at this issue on and off but didn't come up with a solution. Glad it wasn't a problem with my collection classes.
